# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c95e9f5657e654349f6a5c30c113e83eea5d870053b3d94ef986947768c49c958258b83b785ec28ff404804915ad093c2ce18e4aa82bb58204a6f79227797a49

test:
  secret_key_base: db6d0eda029dc5be01aefd89260d51763e1e41935f249654cf178431fb52d88c952091ba6d5dd0f76f81fb0128da1cba4f15869bf57d72fdd7858f945ac43483

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
